CREATE TABLE deliveries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_date date,
    supplier_id    BIGINT,
    CONSTRAINT pk_deliveries PRIMARY KEY (id)
);

CREATE TABLE delivery_item
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_id    BIGINT,
    product_id     BIGINT,
    weight         DOUBLE PRECISION                        NOT NULL,
    price_per_unit DOUBLE PRECISION                        NOT NULL,
    total_cost     DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_deliveryitem PRIMARY KEY (id)
);

CREATE TABLE products
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    type VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE suppliers
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_suppliers PRIMARY KEY (id)
);

ALTER TABLE deliveries
    ADD CONSTRAINT FK_DELIVERIES_ON_SUPLIER FOREIGN KEY (supplier_id) REFERENCES suppliers (id);

ALTER TABLE delivery_item
    ADD CONSTRAINT FK_DELIVERYITEM_ON_DELIVERY FOREIGN KEY (delivery_id) REFERENCES deliveries (id);

ALTER TABLE delivery_item
    ADD CONSTRAINT FK_DELIVERYITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

INSERT INTO suppliers (name)
VALUES ('Amazon'),
       ('Ebay'),
       ('Aliexpress');

INSERT INTO products (type, name)
VALUES ('Зелёная', 'Груша'),
       ('Желтая', 'Груша'),
       ('Красное', 'Яблоко'),
       ('Золотое', 'Яблоко');